version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: password-manager-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wreckvault
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - wreckcloud

  backend-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: password-manager-api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://user:password@postgres-db:5432/wreckvault
    depends_on:
      - postgres-db
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - wreckcloud
    command: npm run dev

  frontend-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: password-manager-client
    ports:
      - "3000:3000" # Vite default
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend-api:5000
    networks:
      - wreckcloud
    # We want development mode with Hot Reloading
    command: npm run dev -- --host

volumes:
  pgdata:

networks:
  wreckcloud:
    driver: bridge
