version: '3.8'

services:
  backend-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: password-manager-api
    ports:
      - "3012:5000"
    environment:
      - PORT=5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - wreckcloud
    command: npm run dev

  frontend-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: password-manager-client
    ports:
      - "3011:3000" # Vite default
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend-api:5000
    networks:
      - wreckcloud
    # We want development mode with Hot Reloading
    command: npm run dev -- --host

networks:
  wreckcloud:
    driver: bridge
